META_ARC: "siamrpn_alex_dwxcorr"

DATASET:
    NAMES:
        - 'VID'

    VID:
        NUM_USE: -1

GRAD:
    START_EPOCH: 0
    RESUME: False
    RESUME_PATH: ''
    BATCH_SIZE: 16
    EPOCHS: 50
    LR: 0.001
    WEIGHT_DECAY: 0.0005
    PRETRAIN_PATH: './snapshot/alexnet/checkpoint_e46.pth'
    SNAPSHOT_DIR: './snapshot/grad_single_loss'
    LOG_DIR: './logs/alexnet_grad_single_loss'

    KWARGS:
        input_channels: 256
        output_channels: 256


