MODEL_ARC: "GradSiamModel"

DATASET:
    NAMES:
        - 'VID'
        - 'COCO'
        - 'DET'

    EXAMPLAR:
        SHIFT: 4
        SCALE: 0.05
        BLUR: 0.0
        FLIP: 0.0
        COLOR: 1.0

    SEARCH:
        SHIFT: 64
        SCALE: 0.18
        BLUR: 0.2
        FLIP: 0.0
        COLOR: 1.0

GRAD:
    START_EPOCH: 0
    RESUME: False
    RESUME_PATH: ''
    BATCH_SIZE: 128
    EPOCHS: 50
    LR: 0.001
    WEIGHT_DECAY: 0.0005
    PRETRAIN_PATH: './snapshot/alexnet/checkpoint_e46.pth'
    SNAPSHOT_DIR: './snapshot/grad_single_loss_multi_data'
    LOG_DIR: './logs/alexnet_grad_single_loss_multi_data'

    KWARGS:
        input_channels: 256
        output_channels: 256


