META_ARC: "siamrpn_alex_dwxcorr"

DATASET:
    NAMES:
        - 'VID'

    VID:
        NUM_USE: -1

GRAD:
    BATCH_SIZE: 64
    EPOCHS: 50
    LR: 0.001
    WEIGHT_DECAY: 0.0005
    PRETRAIN_PATH: './snapshot/alexnet/checkpoint_e46.pth'
    SNAPSHOT_DIR: './snapshot/grad'
    LOG_DIR: './logs/alexnet_grad'

    KWARGS:
        input_channels: 256
        output_channels: 256


