META_ARC: "siamrpn_mobilenetv2_dwxcorr"

BACKBONE:
    TYPE: "mobilenetv2"
    TRAIN_LAYERS: ['layer3', 'layer5','layer7']
    TRAIN_EPOCH: 10
    LAYERS_LR: 0.1
    KWARGS:
        used_layers: [3, 5, 7]
        width_mult: 1.4  


ADJUST:
    USE: True
    TYPE: "AdjustAllLayer"
    KWARGS:
        in_channels: [48, 136, 448] #because use width_mult=1.0
        out_channels: [256, 256, 256]

RPN:
    TYPE: 'MultiRPN'
    KWARGS:
        in_channels: [256, 256, 256]
        weighted: False

ANCHOR:
    STRIDE: 8
    RATIOS: [0.33, 0.5, 1, 2, 3]
    SCALES: [8]

TRACK:
    TYPE: 'SiamRPNTracker'
    PENALTY_K: 0.04
    WINDOW_INFLUENCE: 0.4
    LR: 0.5
    EXAMPLAR_SIZE: 127
    INSTANCE_SIZE: 255
    BASE_SIZE: 8  #NOTE: because the template map is crop to 7x7, so the base_size is needed.

TRAIN:
    EPOCHS: 50
    START_EPOCH: 44
    BATCH_SIZE: 36 
    RESUME: True
    RESUME_PATH: './snapshot/mobilenetv2/checkpoint_e44.pth'
    PRETRAIN: False
    PRETRAIN_PATH: ''
    BACKBONE_PRETRAIN: True
    BACKBONE_PATH: './pretrained_models/mobilenetv2_1_4.pth'
    SNAPSHOT_DIR: './snapshot/mobilenetv2'
    LOG_DIR: './logs/mobilenetv2'
    OUTPUT_SIZE: 25
    LR:
        TYPE: 'log'
        KWARGS:
            start_lr: 0.005
            end_lr: 0.0005
    LR_WARMUP:
        TYPE: 'step'
        EPOCH: 5
        KWARGS:
            start_lr: 0.001
            end_lr: 0.005
            step: 1

DATASET:
    NAMES:
    - 'VID'
    - 'COCO'
    - 'DET'

    EXAMPLAR:
        SHIFT: 4
        SCALE: 0.05
        BLUR: 0.0
        FLIP: 0.0
        COLOR: 1.0

    SEARCH:
        SHIFT: 64
        SCALE: 0.18
        BLUR: 0.2
        FLIP: 0.0
        COLOR: 1.0

    NEG: 0.2
    GRAY: 0.0
