MODEL_ARC: "PruningSiamModel"

BACKBONE:
    TYPE: "mobilenetv2"
    TRAIN_LAYERS: ['layer3','layer5','layer7']
    TRAIN_EPOCH: 10
    LAYERS_LR: 0.1
    KWARGS:
        used_layers: [3, 5, 7]
        width_mult: 1.4


ADJUST:
    USE: True
    TYPE: "AdjustAllLayer"
    KWARGS:
        in_channels: [44, 134, 448]  # without make_divible
        out_channels: [256, 256, 256]

RPN:
    TYPE: 'MultiRPN'
    KWARGS:
        in_channels: [256, 256, 256]
        weighted: False

ANCHOR:
    STRIDE: 8
    RATIOS: [0.33, 0.5, 1, 2, 3]
    SCALES: [8]

TRACK:
    TYPE: 'SiamRPNTracker'
    PENALTY_K: 0.04
    WINDOW_INFLUENCE: 0.4
    LR: 0.5
    EXAMPLAR_SIZE: 127
    INSTANCE_SIZE: 255
    BASE_SIZE: 8  # NOTE: because the template map is crop to 7x7, so the base_size is needed.

TRAIN:
    EPOCHS: 70
    START_EPOCH: 24
    BATCH_SIZE: 32
    NUM_WORKERS: 4
    RESUME: True
    RESUME_PATH: './snapshot/mobilenetv2_lr/checkpoint_e24.pth'
    PRETRAIN: False
    PRETRAIN_PATH: ''
    BACKBONE_PRETRAIN: True
    BACKBONE_PATH: './pretrained_models/mobilenetv2_1_4.pth'
    SNAPSHOT_DIR: './snapshot/mobilenetv2_lr'
    LOG_DIR: './logs/mobilenetv2_lr'
    OUTPUT_SIZE: 25
    LOG_GRAD: True
    LR:
        TYPE: 'log'
        KWARGS:
            start_lr: 0.01
            end_lr: 0.001
    LR_WARMUP:
        WARMUP: False # the value is used for lr_scheduler
        TYPE: 'step'
        EPOCH: 5
        KWARGS:
            start_lr: 0.005
            end_lr: 0.01
            step: 1

DATASET:
    NAMES:
        - 'VID'
        - 'COCO'
        - 'DET' # for pruning finetune use
        - 'YOUTUBEBB'
#    VID:
#        NUM_USE: -1
    EXAMPLAR:
        SHIFT: 4
        SCALE: 0.05
        BLUR: 0.0
        FLIP: 0.0
        COLOR: 1.0

    SEARCH:
        SHIFT: 64
        SCALE: 0.18
        BLUR: 0.2
        FLIP: 0.0
        COLOR: 1.0

    NEG: 0.2
    GRAY: 0.0
    VIDEO_PER_EPOCH: -1

PRUNING:
    KEEP_RATE: 0.75
    BATCH_SIZE: 24
    BASE_LR: 0.001
    MOMENTUM: 0.9
    WEIGHT_DECAY: 0.0005
    EPOCHS: 20
    START_EPOCH: 4
    RESUME: True
    RESUME_PATH: './snapshot/mobilenetv2_gm_0_75_new/checkpoint_e4.pth'

    LOG_DIR: './logs/mobilenetv2_gm_0_75_new'
    SNAPSHOT_DIR: './snapshot/mobilenetv2_gm_0_75_new'
    LOG_GRAD: False
    GRAD_CLIP: False
    PRETRAIN_PATH: './pretrained_models/siamrpn_mobi.pth'
    LR:
        TYPE: 'log'
        KWARGS:
            start_lr: 0.005
            end_lr: 0.001

    FINETUNE:
        BATCH_SIZE: 128
        BASE_LR: 0.001
        MOMENTUM: 0.9
        WEIGHT_DECAY: 0.0005
        EPOCHS: 20
        START_EPOCH: 0
        RESUME: False
        RESUME_PATH: ''
        LOG_DIR: './logs/mobilenetv2_gm_0_75_finetune'
        SNAPSHOT_DIR: './snapshot/mobilenetv2_gm_0_75_finetune'
        LOG_GRAD: False
        GRAD_CLIP: False
        PRETRAIN_PATH: './snapshot/mobilenetv2_sfp_0_75_new/checkpoint_e2.pth'
        LR:
            TYPE: 'log'
            KWARGS:
                start_lr: 0.0025
                end_lr: 0.0005
