MODEL_ARC: "BaseSiamModel"

BACKBONE:
    TYPE: "resnet50"
    TRAIN_LAYERS: ['layer2','layer3','layer4']
    TRAIN_EPOCH: 10
    LAYERS_LR: 0.1
    KWARGS:
        used_layers: [2, 3, 4]


ADJUST:
    USE: True
    TYPE: "AdjustAllLayer"
    KWARGS:
        in_channels: [512, 1024, 2048]
        out_channels: [256, 256, 256]

RPN:
    TYPE: 'MultiRPN'
    KWARGS:
        in_channels: [256, 256, 256]
        weighted: True

ANCHOR:
    STRIDE: 8
    RATIOS: [0.33, 0.5, 1, 2, 3]
    SCALES: [8]

TRACK:
    TYPE: 'SiamRPNTracker'
    PENALTY_K: 0.04
    WINDOW_INFLUENCE: 0.44
    LR: 0.33
    EXAMPLAR_SIZE: 127
    INSTANCE_SIZE: 255
    BASE_SIZE: 8  # NOTE: because the template map is crop to 7x7, so the base_size is needed.

TRAIN:
    EPOCHS: 20
    START_EPOCH: 0
    BATCH_SIZE: 28
    RESUME: False
    RESUME_PATH: ''
    PRETRAIN: False
    PRETRAIN_PATH: ''
    BACKBONE_PRETRAIN: True
    BACKBONE_PATH: './pretrained_models/resnet50.pth'
    SNAPSHOT_DIR: './snapshot/resnet50'
    LOG_DIR: './logs/resnet50'
    OUTPUT_SIZE: 25
    LOG_GRAD: False
    LR:
        TYPE: 'log'
        KWARGS:
            start_lr: 0.005
            end_lr: 0.0005
    LR_WARMUP:
        TYPE: 'step'
        EPOCH: 5
        KWARGS:
            start_lr: 0.001
            end_lr: 0.005
            step: 1
DATASET:
    NAMES:
        - 'VID'
        - 'COCO'
        - 'DET'
        - 'YOUTUBEBB'

    EXAMPLAR:
        SHIFT: 4
        SCALE: 0.05
        BLUR: 0.0
        FLIP: 0.0
        COLOR: 1.0

    SEARCH:
        SHIFT: 64
        SCALE: 0.18
        BLUR: 0.2
        FLIP: 0.0
        COLOR: 1.0

    NEG: 0.2
    GRAY: 0.0
